SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(AVG(b.REVIEW_SCORE),2) AS 'SCORE'
FROM REST_INFO a, REST_REVIEW b
WHERE a.REST_ID = b.REST_ID
AND a.ADDRESS LIKE '서울%'
GROUP BY a.REST_ID
ORDER BY AVG(b.REVIEW_SCORE) DESC, a.FAVORITES DESC;